name: conductor 
on:
  workflow_dispatch:
    inputs:
      deployment_tag:
        description: 'Tag to deploy'
        required: false
        default: 'v1.0.0'
      target_environments:
        description: 'Comma-separated list of target environments (e.g., Development,QA,UAT)'
        required: false
        default: 'Development,QA,UAT'
  push:
    branches:
      - main
permissions: 
  contents: read
jobs: 
  wip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set PR Branch Info
        id: pr_branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          BASE_REF="origin/${{ github.event.pull_request.base.ref }}"
          HEAD_REF="origin/${{ github.event.pull_request.head.ref }}"
          echo "Base ref: $BASE_REF"
          echo "Head ref: $HEAD_REF"
          echo "base_ref=$BASE_REF" >> $GITHUB_OUTPUT
          echo "head_ref=$HEAD_REF" >> $GITHUB_OUTPUT






