name: conductor 
on:
  workflow_dispatch:
    inputs:
      deployment_tag:
        description: 'Tag to deploy'
        required: false
        default: 'v1.0.0'
      target_environments:
        description: 'Comma-separated list of target environments (e.g., Development,QA,UAT)'
        required: false
        default: 'Development,QA,UAT'
  push:
    branches:
      - main
permissions: 
  contents: read
jobs: 
  wip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version
        id: set_version
        uses: ./.github/actions/set-version
        with:
          event_name: ${{ github.event_name }}
          deployment_tag: ${{ github.event.inputs.deployment_tag }}
          ref_name: ${{ github.ref_name }}
          run_number: ${{ github.run_number }}

      - name: Print Version
        shell: pwsh
        run: |
          write-host "Version: ${{ steps.set_version.outputs.version }}"

      - name: Set Target Environments
        id: set_environments
        uses: ./.github/actions/set-target-environment
        with:
          event_name: ${{ github.event_name }}
          target_environments: ${{ github.event.inputs.target_environments }}
      
      - name: Print Target Environments
        shell: pwsh
        run: |
          write-host "Target Environments: ${{ steps.set_environments.outputs.target_environments }}"

      - name: Get Builds
        id: get_builds
        uses: ./.github/actions/nx-get-builds
        with:
          projects: ""
          base_ref: "main"
          node_version: "21"

      - name: Print Builds
        shell: pwsh
        run: |
          write-host "Builds: ${{ steps.get_builds.outputs.builds }}"






