name: conductor 
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: 
  contents: read
jobs: 
  wip:
    runs-on: ubuntu-latest
    outputs: 
      wip_output: ${{ steps.wip.outputs.wip_output }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run WIP script Steps 
        id: wip
        shell: pwsh
        run: |
          $out = .github/workflows/scripts/wip.ps1 -serialized_parameter1 '{"param1":"conductorjob1","param2":"conductorjob2","param3":"false"}'
          $out = $out.Trim()
          "wip_output=$out" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Wip Output Step
        shell: pwsh
        run: |
          write-host "WIP output: ${{ steps.wip.outputs.wip_output }}"

  wip_output_job:
    runs-on: ubuntu-latest
    needs: wip
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print WIP Output
        shell: pwsh
        run: |
          write-host "WIP output from previous job: ${{ needs.wip.outputs.wip_output }}"


  wip_input_reusable_job:
    uses: ./.github/workflows/orchestra1.yml

  wip_output_reusable_job:
    runs-on: ubuntu-latest
    needs: wip_input_reusable_job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print WIP Output from Reusable Job
        shell: pwsh
        run: |
          write-host "WIP output from reusable job: ${{ needs.wip_input_reusable_job.outputs.reusable_output }}"
