name: conductor 
on:
  workflow_dispatch:
    inputs:
      deployment_tag:
        description: 'Tag to deploy'
        required: false
        default: 'v1.0.0'
      target_environments:
        description: 'Comma-separated list of target environments (e.g., Development,QA,UAT)'
        required: false
        default: 'Development,QA,UAT'
  push:
    branches:
      - main
permissions: 
  contents: read
jobs: 
  wip:
    runs-on: ubuntu-latest
    outputs: 
      wip_output: ${{ steps.wip.outputs.wip_output }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run WIP script Steps 
        id: wip
        shell: pwsh
        run: |
          $out = .github/workflows/scripts/wip.ps1 -serialized_parameter1 '{"param1":"conductorjob1","param2":"conductorjob2","param3":"false"}'
          $out = $out.Trim()
          "wip_output=$out" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Wip Output Step
        shell: pwsh
        run: |
          write-host "WIP output: ${{ steps.wip.outputs.wip_output }}"

      - name: Set Version
        id: set_version
        uses: ./.github/actions/set-version
        with:
          event_name: ${{ github.event_name }}
          deployment_tag: ${{ github.event.inputs.deployment_tag }}
          ref_name: ${{ github.ref_name }}
          run_number: ${{ github.run_number }}

      - name: Print Version
        shell: pwsh
        run: |
          write-host "Version: ${{ steps.set_version.outputs.version }}"

      - name: Print Target Environments
        id: print_environments
        uses: ./.github/actions/set-target-environment
        with:
          event_name: ${{ github.event_name }}
          target_environments: ${{ github.event.inputs.target_environments }}
      
      - name: Print Target Environments Step
        shell: pwsh
        run: |
          write-host "Target Environments: ${{ steps.print_environments.outputs.target_environments }}"





















          
  wip_output_job:
    runs-on: ubuntu-latest
    needs: wip
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print WIP Output
        shell: pwsh
        run: |
          write-host "WIP output from previous job: ${{ needs.wip.outputs.wip_output }}"


  wip_input_reusable_job:
    uses: ./.github/workflows/orchestra1.yml

  wip_output_reusable_job:
    runs-on: ubuntu-latest
    needs: wip_input_reusable_job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print WIP Output from Reusable Job
        shell: pwsh
        run: |
          write-host "WIP output from reusable job: ${{ needs.wip_input_reusable_job.outputs.reusable_output }}"
