name: orchestra1 
on:
  workflow_call: 
    inputs: 
      param1: 
        type: string
        default: "orchestra1job1"
      param2: 
        type: string
        default: "orchestra1job2"
      param3: 
        type: boolean
        default: true
    outputs:
      reusable_output:
        description: "Output from reusable workflow"
        value: ${{ jobs.orchestra1.outputs.orchestra1_output }}
permissions: 
  contents: read
jobs: 
  orchestra1:
    runs-on: ubuntu-latest
    outputs: 
      orchestra1_output: ${{ steps.orchestra1.outputs.orchestra1_output }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run WIP script Steps 
        id: orchestra1
        shell: pwsh
        run: |
          $out = .github/workflows/scripts/wip.ps1 -serialized_parameter1 '{"param1":"${{ inputs.param1 }}","param2":"${{ inputs.param2 }}","param3":"${{ inputs.param3 }}"}'
          "orchestra1_output=$out" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
